<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Insertar categorías
        DB::table('categorias')->insert([
            ['nombre' => 'Vinilo', 'descripcion' => 'Pintura a base de agua para interiores'],
            ['nombre' => 'Esmalte', 'descripcion' => 'Pintura resistente para metal y madera'],
            ['nombre' => 'Impermeabilizante', 'descripcion' => 'Protección contra humedad'],
        ]);

        // 2. Insertar acabados
        DB::table('acabados')->insert([
            ['nombre' => 'Mate', 'descripcion' => 'Sin brillo, elegante'],
            ['nombre' => 'Brillante', 'descripcion' => 'Alto brillo, fácil limpieza'],
            ['nombre' => 'Satinado', 'descripcion' => 'Brillo medio, versátil'],
        ]);

        // 3. Insertar productos de ejemplo (20 pinturas)
        DB::table('productos')->insert([
            [
                'nombre' => 'Azul Acrilinco Profundo',
                'descripcion' => 'Vinilo azul oscuro corporativo, ideal para salas',
                'marca' => 'Acrilinco',
                'categoria_id' => 1, // Vinilo
                'acabado_id' => 1,   // Mate
                'codigo_color_hex' => '#033380',
                'nombre_color' => 'Azul Oscuro',
                'precio' => 45900,
                'stock' => 25,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/033380/FFFFFF?text=Azul+Oscuro',
            ],
            [
                'nombre' => 'Naranja Acrilinco Energía',
                'descripcion' => 'Esmalte naranja vivo para puertas y rejas',
                'marca' => 'Acrilinco',
                'categoria_id' => 2, // Esmalte
                'acabado_id' => 2,   // Brillante
                'codigo_color_hex' => '#fd5017',
                'nombre_color' => 'Naranja Vivido',
                'precio' => 52000,
                'stock' => 18,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/fd5017/FFFFFF?text=Naranja+Vivido',
            ],
            [
                'nombre' => 'Blanco Acrilinco Pureza',
                'descripcion' => 'Vinilo blanco puro, máximo cubrimiento',
                'marca' => 'Acrilinco',
                'categoria_id' => 1,
                'acabado_id' => 3, // Satinado
                'codigo_color_hex' => '#FFFFFF',
                'nombre_color' => 'Blanco',
                'precio' => 38500,
                'stock' => 40,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/FFFFFF/000000?text=Blanco',
            ],
            [
                'nombre' => 'Gris Claro Acrilinco Nube',
                'descripcion' => 'Vinilo gris claro para ambientes minimalistas',
                'marca' => 'Acrilinco',
                'categoria_id' => 1,
                'acabado_id' => 1,
                'codigo_color_hex' => '#F5F5F5',
                'nombre_color' => 'Gris Claro',
                'precio' => 42000,
                'stock' => 30,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/F5F5F5/000000?text=Gris+Claro',
            ],
            [
                'nombre' => 'Verde Éxito Acrilinco',
                'descripcion' => 'Esmalte verde brillante para detalles',
                'marca' => 'Acrilinco',
                'categoria_id' => 2,
                'acabado_id' => 2,
                'codigo_color_hex' => '#27AE60',
                'nombre_color' => 'Verde Éxito',
                'precio' => 49900,
                'stock' => 12,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/27AE60/FFFFFF?text=Verde+Exito',
            ],
            [
                'nombre' => 'Rojo Error Acrilinco',
                'descripcion' => 'Vinilo rojo intenso para acentos',
                'marca' => 'Acrilinco',
                'categoria_id' => 1,
                'acabado_id' => 1,
                'codigo_color_hex' => '#E74C3C',
                'nombre_color' => 'Rojo',
                'precio' => 44500,
                'stock' => 8,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/E74C3C/FFFFFF?text=Rojo',
            ],
            [
                'nombre' => 'Amarillo Advertencia Acrilinco',
                'descripcion' => 'Esmalte amarillo alta visibilidad',
                'marca' => 'Acrilinco',
                'categoria_id' => 2,
                'acabado_id' => 2,
                'codigo_color_hex' => '#F39C12',
                'nombre_color' => 'Amarillo',
                'precio' => 47000,
                'stock' => 15,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/F39C12/FFFFFF?text=Amarillo',
            ],
            [
                'nombre' => 'Azul Info Acrilinco',
                'descripcion' => 'Vinilo azul claro informativo',
                'marca' => 'Acrilinco',
                'categoria_id' => 1,
                'acabado_id' => 3,
                'codigo_color_hex' => '#3498DB',
                'nombre_color' => 'Azul Claro',
                'precio' => 46000,
                'stock' => 20,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/3498DB/FFFFFF?text=Azul+Claro',
            ],
            [
                'nombre' => 'Gris Oscuro Acrilinco Grafito',
                'descripcion' => 'Esmalte gris oscuro para muebles',
                'marca' => 'Acrilinco',
                'categoria_id' => 2,
                'acabado_id' => 3,
                'codigo_color_hex' => '#2C3E50',
                'nombre_color' => 'Gris Oscuro',
                'precio' => 53000,
                'stock' => 10,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/2C3E50/FFFFFF?text=Gris+Oscuro',
            ],
            [
                'nombre' => 'Gris Medio Acrilinco Neutro',
                'descripcion' => 'Vinilo gris medio versátil',
                'marca' => 'Acrilinco',
                'categoria_id' => 1,
                'acabado_id' => 1,
                'codigo_color_hex' => '#95A5A6',
                'nombre_color' => 'Gris Medio',
                'precio' => 41000,
                'stock' => 22,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/95A5A6/FFFFFF?text=Gris+Medio',
            ],
            [
                'nombre' => 'Vinilo Acrilinco Marfil',
                'descripcion' => 'Color marfil cálido para interiores',
                'marca' => 'Acrilinco',
                'categoria_id' => 1,
                'acabado_id' => 3,
                'codigo_color_hex' => '#FFFFF0',
                'nombre_color' => 'Marfil',
                'precio' => 39900,
                'stock' => 35,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/FFFFF0/000000?text=Marfil',
            ],
            [
                'nombre' => 'Esmalte Acrilinco Negro',
                'descripcion' => 'Negro brillante para herrería',
                'marca' => 'Acrilinco',
                'categoria_id' => 2,
                'acabado_id' => 2,
                'codigo_color_hex' => '#000000',
                'nombre_color' => 'Negro',
                'precio' => 55000,
                'stock' => 14,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/000000/FFFFFF?text=Negro',
            ],
            [
                'nombre' => 'Impermeabilizante Acrilinco Blanco',
                'descripcion' => 'Impermeabilizante blanco para techos',
                'marca' => 'Acrilinco',
                'categoria_id' => 3,
                'acabado_id' => 1,
                'codigo_color_hex' => '#FAFAFA',
                'nombre_color' => 'Blanco Hueso',
                'precio' => 68000,
                'stock' => 20,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/FAFAFA/000000?text=Impermeabilizante',
            ],
            [
                'nombre' => 'Vinilo Acrilinco Coral',
                'descripcion' => 'Coral suave para dormitorios',
                'marca' => 'Acrilinco',
                'categoria_id' => 1,
                'acabado_id' => 1,
                'codigo_color_hex' => '#FF7F50',
                'nombre_color' => 'Coral',
                'precio' => 43500,
                'stock' => 17,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/FF7F50/FFFFFF?text=Coral',
            ],
            [
                'nombre' => 'Esmalte Acrilinco Azul Rey',
                'descripcion' => 'Azul intenso para detalles metálicos',
                'marca' => 'Acrilinco',
                'categoria_id' => 2,
                'acabado_id' => 2,
                'codigo_color_hex' => '#4169E1',
                'nombre_color' => 'Azul Rey',
                'precio' => 51000,
                'stock' => 9,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/4169E1/FFFFFF?text=Azul+Rey',
            ],
            [
                'nombre' => 'Vinilo Acrilinco Lavanda',
                'descripcion' => 'Lavanda relajante para espacios zen',
                'marca' => 'Acrilinco',
                'categoria_id' => 1,
                'acabado_id' => 3,
                'codigo_color_hex' => '#E6E6FA',
                'nombre_color' => 'Lavanda',
                'precio' => 47800,
                'stock' => 13,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/E6E6FA/000000?text=Lavanda',
            ],
            [
                'nombre' => 'Esmalte Acrilinco Turquesa',
                'descripcion' => 'Turquesa vibrante para exteriores',
                'marca' => 'Acrilinco',
                'categoria_id' => 2,
                'acabado_id' => 2,
                'codigo_color_hex' => '#40E0D0',
                'nombre_color' => 'Turquesa',
                'precio' => 54000,
                'stock' => 11,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/40E0D0/FFFFFF?text=Turquesa',
            ],
            [
                'nombre' => 'Vinilo Acrilinco Terracota',
                'descripcion' => 'Terracota cálido estilo mediterráneo',
                'marca' => 'Acrilinco',
                'categoria_id' => 1,
                'acabado_id' => 1,
                'codigo_color_hex' => '#E2725B',
                'nombre_color' => 'Terracota',
                'precio' => 48200,
                'stock' => 16,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/E2725B/FFFFFF?text=Terracota',
            ],
            [
                'nombre' => 'Impermeabilizante Acrilinco Rojo',
                'descripcion' => 'Impermeabilizante rojo para cubiertas',
                'marca' => 'Acrilinco',
                'categoria_id' => 3,
                'acabado_id' => 1,
                'codigo_color_hex' => '#B22222',
                'nombre_color' => 'Rojo Ladrillo',
                'precio' => 72000,
                'stock' => 7,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/B22222/FFFFFF?text=Impermeabilizante+Rojo',
            ],
            [
                'nombre' => 'Vinilo Acrilinco Menta',
                'descripcion' => 'Verde menta fresco para cocinas',
                'marca' => 'Acrilinco',
                'categoria_id' => 1,
                'acabado_id' => 3,
                'codigo_color_hex' => '#98FF98',
                'nombre_color' => 'Menta',
                'precio' => 44000,
                'stock' => 19,
                'disponible' => true,
                'imagen_url' => 'https://via.placeholder.com/300x300/98FF98/000000?text=Menta',
            ],
        ]);
    }
}